version: "3.8"
services:

  nginx:
    image: my-nginx
    build:
      context: nginx
      dockerfile: ./Dockerfile
    container_name: my-nginx
    depends_on:
    - angular-client
    restart: unless-stopped
    ports:
    - 80:80
    networks:
    - dockerForDevelopers
  
  angular-client:
    image: angular-client
    build:
        context: angular-client
        dockerfile: ./Dockerfile
    container_name: angular-client
    restart: unless-stopped
    ports:
      - 81:80
    networks:
    - dockerForDevelopers

  api:
    image: api
    build:
        context: api
        dockerfile: ./Dockerfile
    container_name: server
    restart: unless-stopped
    ports:
      - 3001:3001
    networks:
    - dockerForDevelopers

  mongodb:
    image: mongo:latest
    container_name: database
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pZ5FbOZ50GkZ
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    networks:
    - dockerForDevelopers

volumes:
  mongodb:
    driver: local
    
networks:
  dockerForDevelopers:
    driver: bridge